### ISSUE TITLE
drag n drop seems to not work

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [kitlith/GotaSequenceCmd#4]
Whenever I try to drag and drop a .mid file onto any of the batch files, it doesn't seem to do anything. Can someone please help?

**Comment by kitlith** [comment]
I'd need to see the output of the program to say anything about that. Add an extra line containing `pause` to the end of from_midi.bat , drag-n-drop the midi file onto from_midi.bat, and send me the output that should show up in the command line window.

**Comment by ego-lay-atman-bay** [comment]
I'll try that out. Although I did manage to use the converter using the commend line. Took me a while though.

**Comment by kitlith** [comment]
hm. odd that it works via cmdline and not drag-n-drop

**Comment by ego-lay-atman-bay** [comment]
by doing what you suggested, I noticed that the batch file assumes `GotaSequenceCmd.exe` is in the same folder as the batch file. By editing the file to say `"%~dp0\bin\Debug\GotaSequenceCmd.exe" from_midi %1` it works.

sorry it took so long, I just never bothered to get around to doing it.

**Comment by kitlith** [comment]
Ahhhhh, that makes sense.

The batch files were made to be included in a zip file with the binary, and somewhere iirc there is a zip file where this is the case. Not sure why I never uploaded it here as a release.

Was always meant to be a shortcut for people who are intimidated by the command line, not for people who are building it themselves. I'm glad you figured it out!
